---
- name: Create dirs
  file:
    path: '{{ alertmanager_dir }}'
    state: directory

- name: Copy config file
  copy:
    content: '{{ alertmanager_config }}'
    dest: '{{ alertmanager_dir }}/alertmanager.yml'

- name: Pull image
  docker_image:
    source: pull
    name: '{{ alertmanager_image }}'

- set_fact:
    # yamllint disable-line rule:line-length
    alertmanager_container: '{{ alertmanager_container_defaults | combine(alertmanager_container)}}'

- name: Start container
  docker_container: '{{ alertmanager_container }}'
