---
- name: Create dirs
  file:
    path: '{{ alertmanager_dir }}'
    state: directory

- name: Copy config file
  copy:
    content: '{{ alertmanager_config }}'
    dest: '{{ alertmanager_dir }}/alertmanager.yml'

- name: Pull image
  docker_image:
    source: pull
    name: '{{ alertmanager_image }}'

- set_fact:
    # yamllint disable-line rule:line-length
    alertmanager_container: '{{ alertmanager_container_defaults | combine(alertmanager_container)}}'

- name: Start container
  docker_container: '{{ alertmanager_container }}'

- name: Wait for Alertmanager to start
  register: health_check_result
  # yamllint disable rule:line-length
  shell: >-
    docker exec -it {{ alertmanager_container.name }} sh -c
    'apk add --no-cache httpie && http http://localhost:{{ alertmanager_port }}/-/ready/ --check-status --timeout=3'
  retries: 10
  delay: 1
  until: health_check_result.rc == 0
  changed_when: false
