---
# yamllint disable rule:line-length
- name: Create blackbox dir
  file:
    path: '{{ blackbox_dir }}'
    state: directory

- name: Copy config file
  copy:
    content: '{{ blackbox_config }}'
    dest: '{{ blackbox_dir }}/config.yml'

- name: Pull image
  docker_image:
    source: pull
    name: '{{ blackbox_image }}'

- set_fact:
    blackbox_container: '{{ blackbox_container_defaults | combine(blackbox_container )}}'

- set_fact:
    blackbox_container_check: '{{ blackbox_container | combine({
        "name": blackbox_container.name + "-check-config",
        "command": "--config.file=/etc/blackbox_exporter/config.yml --config.check",
        "restart_policy": "no",
        "detach": false,
        "cleanup": true,
      })}}'

- name: Check config
  changed_when: false
  docker_container: '{{ blackbox_container_check }}'

- name: Start container
  docker_container: '{{ blackbox_container }}'
