---
- name: Create grafana dir
  file:
    path: '{{ grafana_dir }}'
    state: directory

- name: Create data sources dir
  file:
    path: '{{ grafana_provisioning_dir }}/datasources'
    state: directory
    recurse: true

- name: Create the data sources file
  copy:
    content: '{{ grafana_data_sources }}'
    dest: '{{ grafana_provisioning_dir }}/datasources/datasources.yml'

- set_fact:
    # yamllint disable-line rule:line-length
    grafana_container: '{{ grafana_container_defaults | combine(grafana_container) }}'

- name: Pull image
  docker_image:
    source: pull
    name: '{{ grafana_container.image }}'

- name: Start container
  # yamllint disable-line rule:line-length
  docker_container: '{{ grafana_container_defaults | combine(grafana_container) }}'

- name: Wait for Grafana to start
  register: health_check_result
  # yamllint disable rule:line-length
  shell: >-
    docker exec -it {{ grafana_container.name }} sh -c
    'apk add --no-cache httpie && http http://localhost:{{ grafana_container.env.GF_SERVER_HTTP_PORT }}/api/health --check-status --timeout=3'
  retries: 10
  delay: 1
  until: health_check_result.rc == 0
  changed_when: false
