---
- name: Create grafana dir
  file:
    path: '{{ grafana_dir }}'
    state: directory

- name: Create data sources dir
  file:
    path: '{{ grafana_provisioning_dir }}/datasources'
    state: directory
    recurse: true

- name: Create the data sources file
  copy:
    content: '{{ grafana_data_sources }}'
    dest: '{{ grafana_provisioning_dir }}/datasources/datasources.yml'

- set_fact:
    # yamllint disable-line rule:line-length
    grafana_container: '{{ grafana_container_defaults | combine(grafana_container) }}'

- name: Pull image
  docker_image:
    source: pull
    name: '{{ grafana_container.image }}'

- name: Start container
  # yamllint disable-line rule:line-length
  docker_container: '{{ grafana_container_defaults | combine(grafana_container) }}'
