---
- name: Create loki dir
  file:
    path: '{{ loki_dir }}'
    state: directory

- name: Copy the loki config file
  copy:
    content: '{{ loki_config }}'
    dest: '{{ loki_dir }}/config.yml'

- name: Pull image
  docker_image:
    source: pull
    name: '{{ loki_image }}'

- set_fact:
    loki_container: '{{ loki_container_defaults | combine(loki_container) }}'

- name: Start container
  docker_container: '{{ loki_container }}'
