---
- name: Create loki dir
  file:
    path: '{{ loki_dir }}'
    state: directory

- name: Copy the loki config file
  copy:
    content: '{{ loki_config }}'
    dest: '{{ loki_dir }}/config.yml'

- name: Pull image
  docker_image:
    source: pull
    name: '{{ loki_image }}'

- set_fact:
    loki_container: '{{ loki_container_defaults | combine(loki_container) }}'

- name: Start container
  docker_container: '{{ loki_container }}'

- name: Wait for Loki to start
  register: health_check_result
  # yamllint disable rule:line-length
  shell: >-
    docker exec -it {{ loki_container.name }} sh -c
    'apk add --no-cache httpie && http http://localhost:{{ loki_port }}/ready --check-status --timeout=3'
  retries: 40
  delay: 2
  until: health_check_result.rc == 0
  changed_when: false
