---
- name: Create prometheus dirs
  notify: restart_prometheus
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ prometheus_dir }}'
    - '{{ prometheus_dir }}/data'

- name: Template prometheus.yml
  notify: restart_prometheus
  copy:
    content: '{{ prometheus_config }}'
    dest: '{{ prometheus_dir }}/prometheus.yml'

- name: Copy rules
  notify: restart_prometheus
  when: 'item.content|length > 0'
  copy:
    content: '{{ item.content }}'
    dest: '{{ item.dest }}'
  loop:
    - content: '{{ prometheus_recording_rules }}'
      dest: '{{ prometheus_dir }}/recording_rules.yml'
    - content: '{{ prometheus_alerting_rules }}'
      dest: '{{ prometheus_dir }}/alerting_rules.yml'

- name: Pull docker image
  docker_image:
    source: pull
    name: '{{ prometheus_image }}'

- name: Check config
  changed_when: false
  # yamllint disable-line rule:line-length
  docker_container: '{{ prometheus_container_defaults | combine(prometheus_container) | combine({
      "name": prometheus_container_name + "-check-config",
      "entrypoint": "/bin/promtool",
      "restart_policy": "no",
      "command": "check config /etc/prometheus/prometheus.yml",
      "detach": false,
      "cleanup": true,
      "ports": [],
    })}}'

- name: Start container
  notify: health_check_prometheus
  # yamllint disable-line rule:line-length
  docker_container: '{{ prometheus_container_defaults | combine(prometheus_container) }}'
