---
- name: Create prometheus dirs
  notify: restart_prometheus
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ prometheus_dir }}'
    - '{{ prometheus_dir }}/data'

- name: Template prometheus.yml
  notify: restart_prometheus
  copy:
    content: '{{ prometheus_config }}'
    dest: '{{ prometheus_dir }}/prometheus.yml'

- name: Copy rules
  notify: restart_prometheus
  when: 'item.content|length > 0'
  copy:
    content: '{{ item.content }}'
    dest: '{{ item.dest }}'
  loop:
    - content: '{{ prometheus_recording_rules }}'
      dest: '{{ prometheus_dir }}/recording_rules.yml'
    - content: '{{ prometheus_alerting_rules }}'
      dest: '{{ prometheus_dir }}/alerting_rules.yml'

- name: Pull docker image
  docker_image:
    source: pull
    name: '{{ prometheus_image }}'

- name: Check config
  changed_when: false
  docker_container: &prometheus_docker_container
    comparisons:
      '*': strict
    image: '{{ prometheus_image }}'
    name: '{{ prometheus_container_name }}-check-config'
    user: root
    entrypoint: '/bin/promtool'
    command: 'check config /etc/prometheus/prometheus.yml'
    detach: false
    cleanup: true
    # yamllint disable-line rule:line-length
    networks: '{{ monitoring_default_docker_networks }} + {{ prometheus_docker_networks }}'
    volumes:
      - '{{ prometheus_dir }}:/etc/prometheus'
      - '{{ prometheus_dir }}/data/:/prometheus/'
    memory: '{{ ansible_memory_mb.real.total * 0.5 }}m'

- name: Start container
  notify: health_check_prometheus
  docker_container:
    <<: *prometheus_docker_container
    name: '{{ prometheus_container_name }}'
    detach: true
    cleanup: false
    restart_policy: unless-stopped
    entrypoint: '/bin/prometheus'
    ports:
      - '127.0.0.1:9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url={{ alertmanager_url }}'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention={{ prometheus_retention_period }}'
