---
- name: Restart prometheus
  listen: restart_prometheus
  notify: health_check_prometheus
  uri:
    url: http://localhost:9090/-/reload
    method: POST
    timeout: 60
  register: restart_prometheus
  retries: 25
  delay: 1
  until: restart_prometheus.status == 200

- name: Health check prometheus
  listen: health_check_prometheus
  uri:
    url: http://localhost:9090/-/healthy
  register: health_check_prometheus
  retries: 25
  delay: 1
  until: health_check_prometheus.status == 200

- name: Restart blackbox exporter
  listen: restart_blackbox
  notify: health_check_blackbox
  docker_container:
    name: '{{ blackbox_container_name }}'
    state: started
    restart: true

- name: Health check blackbox
  listen: health_check_blackbox
  uri:
    url: 'http://localhost:{{ blackbox_port }}'
    status_code: 200
    timeout: 5
  register: health_check_blackbox
  retries: 10
  delay: 1
  until: health_check_blackbox.status == 200
