---
- name: Restart prometheus
  listen: restart_prometheus
  notify: health_check_prometheus
  uri:
    url: http://localhost:9090/-/reload
    method: POST
    timeout: 60
  register: restart_prometheus
  retries: 25
  delay: 1
  until: restart_prometheus.status == 200

- name: Health check prometheus
  listen: health_check_prometheus
  uri:
    url: http://localhost:9090/-/healthy
  register: health_check_prometheus
  retries: 25
  delay: 1
  until: health_check_prometheus.status == 200

- name: Restart alertmanager
  listen: restart_alertmanager
  notify: health_check_alertmanager
  docker_container:
    name: '{{ alertmanager_container_name }}'
    state: started
    restart: true

- name: Health check alertmanager
  listen: health_check_alertmanager
  uri:
    url: http://localhost:9093/-/ready
    status_code: 200
    timeout: 5
  register: health_check_alertmanager
  retries: 10
  delay: 1
  until: health_check_alertmanager.status == 200

- name: restart grafana
  listen: restart_grafana
  notify: health_check_grafana
  docker_container:
    name: '{{ grafana_container_name }}'
    state: started
    restart: true

- name: health check grafana
  listen: health_check_grafana
  uri:
    url: http://localhost:9099/api/health
    status_code: 200
    timeout: 5
  register: health_check_grafana
  retries: 10
  delay: 1
  until: health_check_grafana.status == 200

- name: Restart blackbox exporter
  listen: restart_blackbox
  notify: health_check_blackbox
  docker_container:
    name: '{{ blackbox_container_name }}'
    state: started
    restart: true

- name: Health check blackbox
  listen: health_check_blackbox
  uri:
    url: 'http://localhost:{{ blackbox_port }}'
    status_code: 200
    timeout: 5
  register: health_check_blackbox
  retries: 10
  delay: 1
  until: health_check_blackbox.status == 200

- name: Restart loki
  listen: restart_loki
  notify: health_check_loki
  docker_container:
    image: '{{ loki_image }}'
    name: '{{ loki_container_name }}'
    state: started
    restart: true

- name: Health check loki
  listen: health_check_loki
  uri:
    url: 'http://{{ loki_address }}:{{ loki_port }}/ready'
    status_code: 200
    timeout: 5
  register: health_check_loki
  retries: 40
  delay: 2
  until: health_check_loki.status == 200
