---
- name: Converge
  hosts: localhost
  tasks:
    - name: Create network
      include_role:
        name: ansible-role-prometheus
        tasks_from: docker_network.yml

    - name: Deploy Prometheus
      include_role:
        name: ansible-role-prometheus
        tasks_from: prometheus.yml

    - name: Deploy Alertmanager
      include_role:
        name: ansible-role-prometheus
        tasks_from: alertmanager.yml

    - name: Deploy Grafana
      include_role:
        name: ansible-role-prometheus
        tasks_from: grafana.yml

# http://localhost:9099/api/datasources/proxy/1/api/v1/query?query=1%2B1&time=1590425158.273
