---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: true
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: "${MOLECULE_PYTHON:-../../.venv/bin/python}"
      stdout_callback: yaml
  inventory:
    group_vars:
      all:
        ansible_connection: local
        ansible_become: true
        prometheus_dir: /tmp/prometheus
        alertmanager_dir: /tmp/alertmanager
        grafana_dir: /tmp/grafana
        blackbox_dir: /tmp/blackbox
        loki_dir: /tmp/loki
  playbooks:
    converge: converge.yml
    destroy: destroy.yml

verifier:
  name: testinfra
  directory: ../../tests
