---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: "${MOLECULE_PYTHON:-../../.venv/bin/python}"
      stdout_callback: yaml
  inventory:
    group_vars:
      all:
        prometheus_dir: /tmp/prometheus
        alertmanager_dir: /tmp/alertmanager
        grafana_dir: /tmp/grafana

verifier:
  name: testinfra
  directory: ../../tests
