---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: monitoring
    vpc_subnet_id: subnet-1efffb7b
    image: ami-0c48db26521ca9f07
    instance_type: m5.xlarge
    groups: [consul, consul_server]
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      host_key_checking: false
      pipelining: true
  inventory:
    group_vars:
      all:
        consul_network_range: '172.31.0.0/20'
        molecule_no_log: false
verifier:
  name: testinfra
  directory: ../../tests
  options:
    reruns: '3'
    reruns-delay: '2'
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
